name: CI
on:
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    # Step 1
    - name: Check out
      uses: actions/checkout@v1

    # Step 2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Step 3
    - name: Run gradle test
      run: |
        cd backend
        ./gradlew test
